# Function reference {.doc .doc-index}

## chromake

A snakemake pipeline to align ChIP-seq and ATAC-seq samples.

| | |
| --- | --- |
| [pipelines.chromake](pipelines.chromake.qmd#genomake.pipelines.chromake) | Chromake pipeline |
| [pipelines.chromake.scripts.config](pipelines.chromake.scripts.config.qmd#genomake.pipelines.chromake.scripts.config) | The config module of chromake contains functions to read and write the config file of the chromake pipeline. |
| [pipelines.chromake.scripts.paths](pipelines.chromake.scripts.paths.qmd#genomake.pipelines.chromake.scripts.paths) | The paths module of chromake contains functions to identify the inputs and the files generated by the chromake pipeline. |
| [pipelines.chromake.scripts.config.create_example_config](pipelines.chromake.scripts.config.create_example_config.qmd#genomake.pipelines.chromake.scripts.config.create_example_config) | Create an example genomake/chromake YAML configuration file |
| [pipelines.chromake.scripts.config.update_jobs](pipelines.chromake.scripts.config.update_jobs.qmd#genomake.pipelines.chromake.scripts.config.update_jobs) | Update or add the JOBS section in an existing YAML config. |
| [pipelines.chromake.scripts.config.check_project_and_sequencing](pipelines.chromake.scripts.config.check_project_and_sequencing.qmd#genomake.pipelines.chromake.scripts.config.check_project_and_sequencing) | Ensures that projects with no associated sequencing samples are removed from the config, |
| [pipelines.chromake.scripts.config.remove_sequencing](pipelines.chromake.scripts.config.remove_sequencing.qmd#genomake.pipelines.chromake.scripts.config.remove_sequencing) | Remove an entire sequencing project from the YAML config. |
| [pipelines.chromake.scripts.config.remove_samples](pipelines.chromake.scripts.config.remove_samples.qmd#genomake.pipelines.chromake.scripts.config.remove_samples) | Remove specific samples from a project in the YAML config. |
| [pipelines.chromake.scripts.config.create_samplesheet_from_config](pipelines.chromake.scripts.config.create_samplesheet_from_config.qmd#genomake.pipelines.chromake.scripts.config.create_samplesheet_from_config) | Create a samplesheet table (CSV or Excel) from a YAML config, resolving relative paths |
| [pipelines.chromake.scripts.config.create_config_from_table](pipelines.chromake.scripts.config.create_config_from_table.qmd#genomake.pipelines.chromake.scripts.config.create_config_from_table) | Create a YAML config from a table. Supports SAMPLES and optional INPUT files. |
| [pipelines.chromake.scripts.config.check_sample_files_exist](pipelines.chromake.scripts.config.check_sample_files_exist.qmd#genomake.pipelines.chromake.scripts.config.check_sample_files_exist) | Check if all R1 and R2 FASTQ files listed in the config exist. |
| [pipelines.chromake.scripts.config.check_config_format](pipelines.chromake.scripts.config.check_config_format.qmd#genomake.pipelines.chromake.scripts.config.check_config_format) | Create an example genomake/chromake YAML configuration file |
| [pipelines.chromake.scripts.paths.get_all_fastq_related_paths](pipelines.chromake.scripts.paths.get_all_fastq_related_paths.qmd#genomake.pipelines.chromake.scripts.paths.get_all_fastq_related_paths) | Get the path to the files generated by the pipeline for the samples of all sequencing and projects. |
| [pipelines.chromake.scripts.paths.get_sequencing_fastq_related_paths](pipelines.chromake.scripts.paths.get_sequencing_fastq_related_paths.qmd#genomake.pipelines.chromake.scripts.paths.get_sequencing_fastq_related_paths) | Get the path to the files generated by the pipeline for the samples of a specific sequencing. |