# pipelines.chromake.scripts.paths { #genomake.pipelines.chromake.scripts.paths }

`pipelines.chromake.scripts.paths`

The paths module of chromake contains functions to identify the inputs and the files generated by the chromake pipeline.

## Functions

| Name | Description |
| --- | --- |
| [get_all_fastq_related_paths](#genomake.pipelines.chromake.scripts.paths.get_all_fastq_related_paths) | Get the path to the files generated by the pipeline for the samples of all sequencing and projects. |
| [get_sequencing_fastq_related_paths](#genomake.pipelines.chromake.scripts.paths.get_sequencing_fastq_related_paths) | Get the path to the files generated by the pipeline for the samples of a specific sequencing. |

### get_all_fastq_related_paths { #genomake.pipelines.chromake.scripts.paths.get_all_fastq_related_paths }

```python
pipelines.chromake.scripts.paths.get_all_fastq_related_paths(cfg, mode)
```

Get the path to the files generated by the pipeline for the samples of all sequencing and projects.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | Default    |
|--------|--------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| cfg    | dict   | Dict representing the configuration of an analysis with the chromake pipeline.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | _required_ |
| mode   | str    | String representing the files to get. Accepted values are:     - sequencing (raw fastq)     - multiqc_raw (multiqc report regrouping the fastqc of the raw fastq files)     - cutadapt (fastq after adapter trimming)     - fastqc_trimmed (fastqc reports after the adapter trimming)     - multiqc_trimmed (multiqc report after adapter trimming)     - bam (bam files after alignment with bowtie2)     - bam_filtered (bam files after filtering the non-standard chromosomes)     - bedgraph (bedGrapg files generated by HOMER for UCSC visualisation) | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description           |
|--------|--------|-----------------------|
|        | list   | A list of file paths. |

### get_sequencing_fastq_related_paths { #genomake.pipelines.chromake.scripts.paths.get_sequencing_fastq_related_paths }

```python
pipelines.chromake.scripts.paths.get_sequencing_fastq_related_paths(
    cfg,
    sequencing_name,
    mode,
)
```

Get the path to the files generated by the pipeline for the samples of a specific sequencing.

#### Parameters {.doc-section .doc-section-parameters}

| Name            | Type   | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | Default    |
|-----------------|--------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| cfg             | dict   | Dict representing the configuration of an analysis with the chromake pipeline.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | _required_ |
| sequencing_name | str    | String representing the name of the sequencing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | _required_ |
| mode            | str    | String representing the files to get. Accepted values are:     - sequencing (raw fastq)     - multiqc_raw (multiqc report regrouping the fastqc of the raw fastq files)     - cutadapt (fastq after adapter trimming)     - fastqc_trimmed (fastqc reports after the adapter trimming)     - multiqc_trimmed (multiqc report after adapter trimming)     - bam (bam files after alignment with bowtie2)     - bam_filtered (bam files after filtering the non-standard chromosomes)     - flagstat (output of samtools flagstat on the bam files)     - stats (output of samtools stats on the bam files)     - multiqc_stats (multiqc on the folder containing the stats output) | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description               |
|--------|--------|---------------------------|
|        | list   | A list of all file paths. |