"""
The paths module of chromake contains functions to identify the inputs and the files generated by the chromake pipeline.

"""
from pathlib import Path
import re


def get_all_fastq_related_paths(cfg: dict, mode: str) -> list:
    """
    Get the path to the files generated by the pipeline for the samples of all sequencing and projects.

    Parameters
    ----------
    cfg : dict
        Dict representing the configuration of an analysis with the chromake pipeline.
    
    mode: str
        String representing the files to get. Accepted values are:
            - sequencing (raw fastq)
            - multiqc_raw (multiqc report regrouping the fastqc of the raw fastq files)
            - cutadapt (fastq after adapter trimming)
            - fastqc_trimmed (fastqc reports after the adapter trimming)
            - multiqc_trimmed (multiqc report after adapter trimming)
            - bam (bam files after alignment with bowtie2)
            - bam_filtered (bam files after filtering the non-standard chromosomes)
            - bedgraph (bedGrapg files generated by HOMER for UCSC visualisation)
    
    Returns
    -------
    :
        A list of file paths.
    """
    res = []
    for sequencing_name, sequencing_data in cfg["SEQUENCING"].items():
        base = Path(sequencing_data["PATH"])
        if mode == "sequencing":
            res.append(base)
        elif mode == "fastq_raw":
            for sample in sequencing_data.get("SAMPLES", {}).values():
                if sample["R1"]:
                    res.append(base / sample["R1"])
                if sample["R2"]:
                    res.append(base / sample["R2"])
            if "INPUT" in sequencing_data:
                for sample in sequencing_data.get("INPUT", {}).values():
                    if sample["R1"]:
                        res.append(base / sample["R1"])
                    if sample["R2"]:
                        res.append(base / sample["R2"])
        elif mode == "fastqc_raw":
            for sample in sequencing_data.get("SAMPLES", {}).values():
                if sample["R1"]:
                    res.append(base / "QC/FASTQC/RAW" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R1"]).name))
                if sample["R2"]:
                    res.append(base / "QC/FASTQC/RAW" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R2"]).name))
            if "INPUT" in sequencing_data:
                for sample in sequencing_data.get("INPUT", {}).values():
                    if sample["R1"]:
                        res.append(base / "QC/FASTQC/RAW" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R1"]).name))
                    if sample["R2"]:
                        res.append(base / "QC/FASTQC/RAW" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R2"]).name))
        elif mode == "multiqc_raw":
            res.append(base / "QC/MULTIQC/RAW/multiqc_report.html")
        elif mode == "cutadapt":
            for sample in sequencing_data.get("SAMPLES", {}).values():
                if sample["R1"]:
                    res.append(base / "TRIMMED" / Path(sample["R1"]).name)
                if sample["R2"]:
                    res.append(base / "TRIMMED" / Path(sample["R2"]).name)
            if "INPUT" in sequencing_data:
                for sample in sequencing_data.get("INPUT", {}).values():
                    if sample["R1"]:
                        res.append(base / "TRIMMED" / Path(sample["R1"]).name)
                    if sample["R2"]:
                        res.append(base / "TRIMMED" / Path(sample["R2"]).name)
        elif mode == "fastqc_trimmed":
            for sample in sequencing_data.get("SAMPLES", {}).values():
                if sample["R1"]:
                    res.append(base / "QC/FASTQC/TRIMMED" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R1"]).name))
                if sample["R2"]:
                    res.append(base / "QC/FASTQC/TRIMMED" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R2"]).name))
            if "INPUT" in sequencing_data:
                for sample in sequencing_data.get("INPUT", {}).values():
                    if sample["R1"]:
                        res.append(base / "QC/FASTQC/TRIMMED" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R1"]).name))
                    if sample["R2"]:
                        res.append(base / "QC/FASTQC/TRIMMED" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R2"]).name))
        elif mode == "multiqc_trimmed":
            res.append(base / "QC/MULTIQC/TRIMMED/multiqc_report.html")
        elif mode == "bam":
            for sample_name in sequencing_data["SAMPLES"].keys():
                res.append(base / "BAM" / (sample_name + ".bam"))
            if "INPUT" in sequencing_data:
                for sample_name in sequencing_data["INPUT"].keys():
                    res.append(base / "BAM" / (sample_name + ".bam"))
        elif mode == "bam_filtered":
            for sample_name in sequencing_data["SAMPLES"].keys()():
                res.append(base / "BAM" / (sample_name + "_filtered.bam"))
            if "INPUT" in sequencing_data:
                for sample_name in sequencing_data["INPUT"].keys():
                    res.append(base / "BAM" / (sample_name + "_filtered.bam"))
        elif mode == "bedgraph":
            for sample_name in sequencing_data["SAMPLES"].keys():
                res.append(base / "HOMER" / (sample_name + "_UCSC_track.bedGraph"))
            if "INPUT" in sequencing_data:
                for sample_name in sequencing_data["INPUT"].keyss():
                    res.append(base / "HOMER" / (sample_name + "_UCSC_track.bedGraph"))  
        elif mode == "bed":
            for sample_name in sequencing_data["SAMPLES"].keys():
                res.append(base / "BED" / (sample_name + ".bed"))
            if "INPUT" in sequencing_data:
                for sample_name in sequencing_data["INPUT"].keys():
                    res.append(base / "BED" / (sample_name + ".bed"))
        elif mode == "bed_sorted":
            for sample_name in sequencing_data["SAMPLES"].keyss():
                res.append(base / "BED" / (sample_name + "_sorted.bed"))
            if "INPUT" in sequencing_data:
                for sample_name in sequencing_data["INPUT"].keys():
                    res.append(base / "BED" / (sample_name + "_sorted.bed"))
        else:
            print(f"There is an error, chromake.scripts.path.get_path dont recognize the {mode} mode!")      
    return res
        
def get_sequencing_fastq_related_paths(cfg: dict,
                                       sequencing_name: str,
                                       mode: str) -> list:
    """
    Get the path to the files generated by the pipeline for the samples of a specific sequencing.

    Parameters
    ----------
    cfg : dict
        Dict representing the configuration of an analysis with the chromake pipeline.
    
    sequencing_name: str
        String representing the name of the sequencing
    
    mode: str
        String representing the files to get. Accepted values are:
            - sequencing (raw fastq)
            - multiqc_raw (multiqc report regrouping the fastqc of the raw fastq files)
            - cutadapt (fastq after adapter trimming)
            - fastqc_trimmed (fastqc reports after the adapter trimming)
            - multiqc_trimmed (multiqc report after adapter trimming)
            - bam (bam files after alignment with bowtie2)
            - bam_filtered (bam files after filtering the non-standard chromosomes)
            - flagstat (output of samtools flagstat on the bam files)
            - stats (output of samtools stats on the bam files)
            - multiqc_stats (multiqc on the folder containing the stats output)
    
    Returns
    -------
    :
        A list of all file paths.
    """
    res = []
    if sequencing_name in cfg["SEQUENCING"].keys():
        base = Path(cfg["SEQUENCING"][sequencing_name]["PATH"])
        if mode == "sequencing":
            res.append(base)
        elif mode == "fastq_raw":
            for sample in cfg["SEQUENCING"][sequencing_name].get("SAMPLES", {}).values():
                if sample["R1"]:
                    res.append(base / sample["R1"])
                if sample["R2"]:
                    res.append(base / sample["R2"])
            if "INPUT" in cfg["SEQUENCING"][sequencing_name]:
                for sample in cfg["SEQUENCING"][sequencing_name].get("INPUT", {}).values():
                    if sample["R1"]:
                        res.append(base / sample["R1"])
                    if sample["R2"]:
                        res.append(base / sample["R2"])
        elif mode == "fastqc_raw":
            for sample in cfg["SEQUENCING"][sequencing_name].get("SAMPLES", {}).values():
                if sample["R1"]:
                    res.append(base / "QC/FASTQC/RAW" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R1"]).name))
                if sample["R2"]:
                    res.append(base / "QC/FASTQC/RAW" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R2"]).name))
            if "INPUT" in cfg["SEQUENCING"][sequencing_name]:
                for sample in cfg["SEQUENCING"][sequencing_name].get("INPUT", {}).values():
                    if sample["R1"]:
                        res.append(base / "QC/FASTQC/RAW" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R1"]).name))
                    if sample["R2"]:
                        res.append(base / "QC/FASTQC/RAW" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R2"]).name))
        elif mode == "multiqc_raw":
            res.append(base / "QC/MULTIQC/RAW/multiqc_report.html")
        
        elif mode == "cutadapt":
            for sample in cfg["SEQUENCING"][sequencing_name].get("SAMPLES", {}).values():
                if sample["R1"]:
                    res.append(base / "TRIMMED" / Path(sample["R1"]).name)
                if sample["R2"]:
                    res.append(base / "TRIMMED" / Path(sample["R2"]).name)
            if "INPUT" in cfg["SEQUENCING"][sequencing_name]:
                for inp in cfg["SEQUENCING"][sequencing_name].get("SAMPLES", {}).values():
                    if sample["R1"]:
                        res.append(base / "TRIMMED" / Path(inp["R1"]).name)
                    if sample["R2"]:
                        res.append(base / "TRIMMED" / Path(inp["R2"]).name)
        elif mode == "fastqc_trimmed":
            for sample in cfg["SEQUENCING"][sequencing_name].get("SAMPLES", {}).values():
                if sample["R1"]:
                    res.append(base / "QC/FASTQC/TRIMMED" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R1"]).name))
                if sample["R2"]:
                    res.append(base / "QC/FASTQC/TRIMMED" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(sample["R2"]).name))
            if "INPUT" in cfg["SEQUENCING"][sequencing_name]:
                for inp in cfg["SEQUENCING"][sequencing_name].get("SAMPLES", {}).values():
                    if sample["R1"]:
                        res.append(base / "QC/FASTQC/TRIMMED" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(inp["R1"]).name))
                    if sample["R2"]:
                        res.append(base / "QC/FASTQC/TRIMMED" / re.sub(r"\.fastq(\.gz)?$", "_fastqc.html", Path(inp["R2"]).name))
        elif mode == "multiqc_trimmed":
            res.append(base / "QC/MULTIQC/TRIMMED/multiqc_report.html")
        elif mode == "bam":
            for sample_name in cfg["SEQUENCING"][sequencing_name]["SAMPLES"].keys():
                res.append(base / "BAM" / (sample_name + ".bam"))
            if "INPUT" in cfg["SEQUENCING"][sequencing_name]:
                for sample_name in cfg["SEQUENCING"][sequencing_name]["INPUT"].keys():
                    res.append(base / "BAM" / (sample_name + ".bam"))
        elif mode == "bam_filtered":
            for sample_name in cfg["SEQUENCING"][sequencing_name]["SAMPLES"].keys():
                res.append(base / "BAM" / (sample_name + "_filtered.bam"))
            if "INPUT" in cfg["SEQUENCING"][sequencing_name]:
                for sample_name in cfg["SEQUENCING"][sequencing_name]["SAMPLES"].keys():
                    res.append(base / "BAM" / (sample_name + "_filtered.bam"))
        elif mode == "flagstat":
            for sample_name in cfg["SEQUENCING"][sequencing_name]["SAMPLES"].keys():
                res.append(base / "QC/flagstat" / (sample_name + "_flagstat.txt"))
            if "INPUT" in cfg["SEQUENCING"][sequencing_name]:
                for sample_name in cfg["SEQUENCING"][sequencing_name]["SAMPLES"].keys():
                    res.append(base / "QC/flagstat" / (sample_name + "_flagstat.txt"))
        elif mode == "stats":
            for sample_name in cfg["SEQUENCING"][sequencing_name]["SAMPLES"].keys():
                res.append(base / "QC/stats" / (sample_name + "_stats.txt"))
            if "INPUT" in cfg["SEQUENCING"][sequencing_name]:
                for sample_name in cfg["SEQUENCING"][sequencing_name]["SAMPLES"].keys():
                    res.append(base / "QC/stats" / (sample_name + "_stats.txt"))
        elif mode == "multiqc_stats":
            res = base / "QC/MULTIQC/STATS/multiqc_report.html"
        elif mode == "bed":
            for sample_name in cfg["SEQUENCING"][sequencing_name]["SAMPLES"].keys():
                res.append(base / "BED" / (sample_name + ".bed"))
            if "INPUT" in cfg["SEQUENCING"][sequencing_name]:
                for sample_name in cfg["SEQUENCING"][sequencing_name]["INPUT"].keys():
                    res.append(base / "BED" / (sample_name + ".bed"))
        elif mode == "bed_sorted":
            for sample_name in cfg["SEQUENCING"][sequencing_name]["SAMPLES"].keys():
                res.append(base / "BED" / (sample_name + "_sorted.bed"))
            if "INPUT" in cfg["SEQUENCING"][sequencing_name]:
                for sample_name in cfg["SEQUENCING"][sequencing_name]["SAMPLES"].keys():
                    res.append(base / "BED" / (sample_name + "_sorted.bed"))
    else:
        print(f"There is an error, the configuration file don't contains a {sequencing_name} project!")
    return res


